spring:
  application:
    name: app-microservice-cuenta-app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cuenta_db}
    username: ${SPRING_DATASOURCE_USERNAME:cuenta_user}
    password: ${SPRING_DATASOURCE_PASSWORD:cuenta_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:rabbit_user}
    password: ${SPRING_RABBITMQ_PASSWORD:rabbit_pass}

server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
